# Generated by Django 4.2.7 on 2023-11-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shop_password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
